/**
 * gen_card_descriptions.js — Extract card descriptions from TM source .ts files
 * Uses CardName enum for accurate name mapping.
 *
 * Usage: node scripts/gen_card_descriptions.js
 */

const fs = require('fs');
const path = require('path');
const {writeGeneratedExtensionFile} = require('./lib/generated-extension-data');

const TM_SRC = path.resolve(__dirname, '../../terraforming-mars/src/server/cards');
const ENUM_FILE = path.resolve(__dirname, '../../terraforming-mars/src/common/cards/CardName.ts');
// 1. Parse CardName enum → { ENUM_KEY: 'Display Name' }
var enumSrc = fs.readFileSync(ENUM_FILE, 'utf8');
var enumMap = {};
var re = /(\w+)\s*=\s*'((?:\\'|[^'])*)'/g;
var m;
while ((m = re.exec(enumSrc)) !== null) enumMap[m[1]] = m[2].replace(/\\'/g, "'");
console.log('CardName enum entries: ' + Object.keys(enumMap).length);

// 2. Recursively find all .ts card files
function findTsFiles(dir) {
  var results = [];
  var entries = fs.readdirSync(dir, { withFileTypes: true });
  for (var e of entries) {
    var full = path.join(dir, e.name);
    if (e.isDirectory()) results = results.concat(findTsFiles(full));
    else if (e.name.endsWith('.ts') && !e.name.endsWith('.d.ts')) results.push(full);
  }
  return results;
}

function collectRenderText(src, callName) {
  var texts = [];
  var patterns = [
    new RegExp("b\\." + callName + "\\(\\s*'([\\s\\S]*?)'", 'g'),
    new RegExp('b\\.' + callName + '\\(\\s*"([\\s\\S]*?)"', 'g'),
  ];
  for (var pattern of patterns) {
    var match;
    while ((match = pattern.exec(src)) !== null) {
      var text = match[1].trim();
      if (text) texts.push(text);
    }
  }
  return texts;
}

var files = findTsFiles(TM_SRC);
console.log('Found ' + files.length + ' .ts card files');

// 3. Extract descriptions
var output = {};
var count = 0, noName = 0, noDesc = 0;

for (var file of files) {
  var src = fs.readFileSync(file, 'utf8');

  // Find CardName.ENUM_KEY
  var nameMatch = src.match(/name:\s*CardName\.(\w+)/);
  if (!nameMatch) { noName++; continue; }

  var enumKey = nameMatch[1];
  var displayName = enumMap[enumKey];
  if (!displayName) { noName++; continue; }

  // Extract description — try single-line first
  var descMatch = src.match(/description:\s*'([^']+)'/);
  if (!descMatch) descMatch = src.match(/description:\s*"([^"]+)"/);

  if (!descMatch) {
    // Try multiline concatenation: description: 'foo' + \n 'bar'
    var multiRe = /description:\s*((?:['"][^'"]*['"]\s*\+?\s*)+)/;
    var multiMatch = src.match(multiRe);
    if (multiMatch) {
      var parts = multiMatch[1].match(/['"]([^'"]*)['"]/g);
      if (parts && parts.length > 0) {
        descMatch = [null, parts.map(function(p) { return p.slice(1, -1); }).join('')];
      }
    }
  }

  var parts = [];
  if (descMatch) parts.push(descMatch[1].trim());
  var renderTexts = collectRenderText(src, 'effect').concat(collectRenderText(src, 'plainText'));
  for (var renderText of renderTexts) {
    if (!parts.some(function(existing) { return existing === renderText; })) parts.push(renderText);
  }

  if (parts.length === 0) { noDesc++; continue; }

  output[displayName] = parts.join(' ');
  count++;
}

console.log('Extracted: ' + count + ' | No name: ' + noName + ' | No description: ' + noDesc);

// 4. Write output
var jsContent = '// Auto-generated by gen_card_descriptions.js\n';
jsContent += '// Source: terraforming-mars/src/server/cards/**/*.ts\n';
jsContent += '// ' + count + ' card descriptions\n';
jsContent += 'const TM_CARD_DESCRIPTIONS = ' + JSON.stringify(output, null, 2) + ';\n';

const out = writeGeneratedExtensionFile('card_descriptions.js', jsContent, 'utf8');
console.log('Written ' + count + ' descriptions to ' + path.relative(process.cwd(), out.canonicalPath));
console.log('Mirrored runtime bundle to ' + path.relative(process.cwd(), out.legacyPath));
