/**
 * gen_card_tags.js — Extract card tags from TM source .ts files
 * Merges with existing card_tags.js, adding missing entries.
 *
 * Usage: node scripts/gen_card_tags.js
 */

const fs = require('fs');
const path = require('path');
const {
  resolveGeneratedExtensionPath,
  writeGeneratedExtensionFile,
} = require('./lib/generated-extension-data');

const TM_SRC = path.resolve(__dirname, '../../terraforming-mars/src/server/cards');
const ENUM_FILE = path.resolve(__dirname, '../../terraforming-mars/src/common/cards/CardName.ts');
const TAG_ENUM_FILE = path.resolve(__dirname, '../../terraforming-mars/src/common/cards/Tag.ts');
const OUTPUT = resolveGeneratedExtensionPath('card_tags.js');

// 1. Parse CardName enum
var enumSrc = fs.readFileSync(ENUM_FILE, 'utf8');
var cardNameMap = {};
var re = /(\w+)\s*=\s*'([^']+)'/g;
var m;
while ((m = re.exec(enumSrc)) !== null) cardNameMap[m[1]] = m[2];
console.log('CardName entries: ' + Object.keys(cardNameMap).length);

// 2. Parse Tag enum → lowercase display names
var tagEnumSrc = fs.readFileSync(TAG_ENUM_FILE, 'utf8');
var tagMap = {};
var tagRe = /(\w+)\s*=\s*'([^']+)'/g;
while ((m = tagRe.exec(tagEnumSrc)) !== null) {
  tagMap[m[1]] = m[2].toLowerCase();
}
console.log('Tag entries: ' + Object.keys(tagMap).length);

// 3. Load existing card_tags.js
var existingSrc = fs.readFileSync(OUTPUT, 'utf8');
eval(existingSrc.replace(/\bconst\b/g, 'var'));
var existingCount = Object.keys(TM_CARD_TAGS).length;
console.log('Existing card_tags entries: ' + existingCount);

// 4. Recursively find all .ts card files
function findTsFiles(dir) {
  var results = [];
  var entries = fs.readdirSync(dir, { withFileTypes: true });
  for (var e of entries) {
    var full = path.join(dir, e.name);
    if (e.isDirectory()) results = results.concat(findTsFiles(full));
    else if (e.name.endsWith('.ts') && !e.name.endsWith('.d.ts')) results.push(full);
  }
  return results;
}

var files = findTsFiles(TM_SRC);

// 5. Extract tags from each card file
var extracted = {};
var noName = 0;

for (var file of files) {
  var src = fs.readFileSync(file, 'utf8');

  var nameMatch = src.match(/name:\s*CardName\.(\w+)/);
  if (!nameMatch) { noName++; continue; }

  var enumKey = nameMatch[1];
  var displayName = cardNameMap[enumKey];
  if (!displayName) { noName++; continue; }

  // Extract tags array: tags: [Tag.FOO, Tag.BAR]
  var tagsMatch = src.match(/tags:\s*\[([\s\S]*?)\]/);
  if (!tagsMatch) continue;

  var tagsStr = tagsMatch[1];
  var tagEntries = tagsStr.match(/Tag\.(\w+)/g);
  if (!tagEntries || tagEntries.length === 0) continue;

  var tags = tagEntries.map(function(t) {
    var key = t.replace('Tag.', '');
    return tagMap[key] || key.toLowerCase();
  });

  // Filter out "clone" and "wild" tags (not real tags for scoring)
  tags = tags.filter(function(t) { return t !== 'clone' && t !== 'wild'; });

  if (tags.length > 0) {
    extracted[displayName] = tags;
  }
}

console.log('Extracted tags for ' + Object.keys(extracted).length + ' cards');

// 6. Merge: add missing, don't overwrite existing
var added = 0;
var updated = 0;

for (var name in extracted) {
  if (!TM_CARD_TAGS[name]) {
    TM_CARD_TAGS[name] = extracted[name];
    added++;
  } else {
    // Check if existing tags are different/incomplete
    var existing = TM_CARD_TAGS[name].sort().join(',');
    var newTags = extracted[name].sort().join(',');
    if (existing !== newTags && extracted[name].length > TM_CARD_TAGS[name].length) {
      // Source has more tags — update
      console.log('  UPDATE: ' + name + ': [' + TM_CARD_TAGS[name] + '] → [' + extracted[name] + ']');
      TM_CARD_TAGS[name] = extracted[name];
      updated++;
    }
  }
}

console.log('Added: ' + added + ' | Updated: ' + updated + ' | Total: ' + Object.keys(TM_CARD_TAGS).length);

// 7. Write output
var sortedKeys = Object.keys(TM_CARD_TAGS).sort();
var lines = [];
for (var key of sortedKeys) {
  lines.push('  ' + JSON.stringify(key) + ': ' + JSON.stringify(TM_CARD_TAGS[key]));
}

var jsContent = '// Card tags — merged from TM source + existing data\n';
jsContent += '// Generated by gen_card_tags.js\n';
jsContent += '// ' + sortedKeys.length + ' cards\n';
jsContent += 'const TM_CARD_TAGS = {\n' + lines.join(',\n') + '\n};\n';

const out = writeGeneratedExtensionFile('card_tags.js', jsContent, 'utf8');
console.log('Written to ' + path.relative(process.cwd(), out.canonicalPath));
console.log('Mirrored to ' + path.relative(process.cwd(), out.legacyPath));
