import json
import re
import sys

with open("C:/Users/Ruslan/tm-tierlist/data/evaluations.json", "r", encoding="utf-8") as f:
    evals = json.load(f)

with open("C:/Users/Ruslan/tm-tierlist/data/all_cards.json", "r", encoding="utf-8") as f:
    all_cards_list = json.load(f)

valid_names = set(c['name'] for c in all_cards_list)
corp_names = set(k for k, v in evals.items() if v.get('type') == 'corporation')

generic_patterns = [
    r'(?i)\b\w+[\s-]+strateg',
    r'(?i)\b\w+[\s-]+(?:tag\s+)?cards?\b',
    r'(?i)^any\s+',
    r'\(.+\)',
    r'(?i)colon(?:y|ies)\s+(?:trade|synerg|bonus)',
    r'(?i)milestone',
    r'(?i)award',
    r'(?i)(?:steel|space|earth|science|venus|building|plant|microbe|animal|jovian|energy|heat|titanium)\s+corps?\b',
    r'(?i)\w+-heavy',
    r'(?i)production\s+(?:prelude|card)',
    r'(?i)люб(?:ая|ой|ые|ое|ого|ую)',
    r'(?i)дорог(?:ие|ой|ая)',
    r'(?i)дешёв(?:ые|ая)',
    r'(?i)\bSP\s+',
    r'(?i)стратег',
    r'(?i)engine\b',
    r'(?i)^все\s',
    r'(?i)\w+-producing',
    r'(?i)animal\s+placement',
    r'(?i)microbe\s+placement',
    r'(?i)floater\s+placement',
    r'(?i)^high[\s-]cost',
    r'(?i)^low[\s-]cost',
    r'(?i)^None\b',
    r'(?i)specific\s+map',
    r'(?i)^Excess\b',
    r'(?i)^Steel\s+dump',
    r'(?i)^MC-prod\b',
    r'(?i)^VP\s+',
    r'(?i)^Nothing\b',
    r'(?i)^When\b',
    r'(?i)^Holding\b',
    r'(?i)^Late[\s-]game\b',
    r'(?i)^Early\b',
    r'(?i)^Against\b',
    r'(?i)^Deny\b',
    r'(?i)^Last[\s-]',
    r'(?i)^2P\b',
    r'(?i)^Stall',
    r'(?i)^Diverse\b',
    r'(?i)^Diversified\b',
    r'(?i)^Aggressive\b',
    r'(?i)^Multi-tag\b',
    r'(?i)^No-tag\b',
    r'(?i)^Single-tag\b',
    r'(?i)^Non-event\b',
    r'(?i)^Wild\s+tag\b',
    r'(?i)^Temperature\b',
    r'(?i)party\b',
    r'(?i)^Chairman\b',
    r'(?i)^Delegate\b',
    r'(?i)^Rush\b',
    r'(?i)^Requirement\b',
    r'(?i)^Standard\s+project',
    r'(?i)^Flexible\b',
    r'(?i)^Greenery\b',
    r'(?i)^City\b',
    r'(?i)^Ocean\b',
    r'(?i)^Special\s+tile',
    r'(?i)^Board\s+presence',
    r'(?i)^Ground\s+game',
    r'(?i)^Strong\s+prelude',
    r'(?i)^Floater\b(?!\s+(?:Technology|Urbanism))',
    r'(?i)^Heat\b',
    r'(?i)^Energy\b(?!\s+(?:Market|Tapping|Saving))',
    r'(?i)^Titanium\b$',
    r'(?i)^Turmoil\b',
    r'(?i)^Political\b',
    r'(?i)^Venus\s+(?:requirement|strategy|tag|heavy)',
    r'(?i)^(?:TR|terraforming)[\s-]+rush',
    r'(?i)^Reds\b',
    r'(?i)^Greens\b',
    r'(?i)^Mars First\b',
    r'(?i)^Scientists\b',
    r'(?i)^Kelvinists\b',
    r'(?i)^Unity\b',
    r'(?i)^Building[\s-]',
    r'(?i)^Plant[\s-]',
    r'(?i)^Science[\s-]',
    r'(?i)^Space[\s-](?!Elevator|Station|Port)',
    r'(?i)^Earth[\s-]tag',
    r'(?i)^Jovian[\s-]',
    r'(?i)\bopponent',
    r'(?i)^Terraform(?:ing)?[\s-](?!Ganymede|Contract|Deal|Control)',
    r'(?i)^Free\b',
    r'(?i)^Cheap\b',
    r'(?i)^Quick\b',
    r'(?i)diverse tag',
    r'(?i)^Steel\s+surplus',
    r'(?i)^Colonies$',
    r'(?i)^Colony[\s-](?!Trade Hub)',
    r'(?i)^IC\b',
    r'(?i)^NRA\b',
    r'(?i)^Moon\b',
    r'(?i)^Heavy\b',
    r'(?i)\bneeds?\b',
    r'(?i)^Card[\s-]',
    r'(?i)^Non-terraform',
    r'(?i)^Asteroid\b(?!\s+(?:Mining|Deflection|Rights|Hollowing|Resources))',
    r'(?i)^Ti[\s-]payable',
    r'(?i)^Zero[\s-]',
    # Russian patterns
    r'(?i)Гибк',
    r'(?i)политик',
]

def is_generic(syn):
    if syn in valid_names:
        return False
    for pattern in generic_patterns:
        if re.search(pattern, syn):
            return True
    return False

manual_fixes = {
    "Point Luna": {"remove": ["Earth tag cards", "Science tag cards"], "add": ["Sponsors", "Interplanetary Trade", "Research"]},
    "CrediCor": {"remove": ["дорогие карты (20+ MC)", "SP Greenery/City", "любая стратегия"], "add": ["Deimos Down", "Terraforming Ganymede", "Large Convoy"]},
    "Manutech": {"remove": ["любая production prelude"], "add": []},
    "Vitor": {"remove": ["VP cards (большинство сильных карт)", "Awards strategy", "Earth tag synergies"], "add": ["Birds", "Colonizer Training Camp", "Pets"]},
    "Tharsis Republic": {"remove": ["City cards", "Mayor milestone", "Landlord award"], "add": ["Open City", "Stanford Torus", "Capital", "Urbanized Area"]},
    "Poseidon": {"remove": ["Colony-placing cards"], "add": ["Mining Colony"]},
    "Philares": {"remove": ["Special tiles", "City cards", "Greenery cards", "Board presence strategy", "Builder milestone"], "add": ["Open City", "Capital", "Urbanized Area", "Mohole Area", "Lava Flows"]},
    "Teractor": {"remove": ["Earth tag cards", "любая expensive стратегия"], "add": ["Sponsors", "Sky Docks", "Interplanetary Trade"]},
    "Valley Trust": {"remove": ["Science tag cards", "Strong prelude pool", "Earth tag synergies"], "add": ["Mars University", "Olympus Conference", "Merger"]},
    "Spire": {"remove": ["Multi-tag cards", "Standard projects", "Science cards", "Earth tag synergies"], "add": ["Soil Studies", "Stratospheric Expedition", "Research", "Sponsored Academies"]},
    "Cheung Shing MARS": {"remove": ["Steel-heavy прелюдии", "Builder milestone", "Building-карты"], "add": ["Smelting Plant", "Mining Operations", "Electro Catapult", "Medical Lab"]},
    "PolderTECH Dutch": {"remove": ["Ocean synergy cards", "Earth tag cards"], "add": ["Kelp Farming", "Luna Governor", "Sponsors", "Lakefront Resorts"]},
    "Nirgal Enterprises": {"remove": ["Production preludes", "Ecologist milestone", "Builder milestone", "Diversifier milestone"], "add": ["Strip Mine", "Business Empire", "Insects", "Cartel"]},
    "Septem Tribus": {"remove": ["Delegate cards", "Turmoil parties", "Wild tag для milestones"], "add": ["Corridors of Power", "Rise To Power", "Cultural Metropolis", "Banned Delegate"]},
    "EcoTec": {"remove": ["Ecologist milestone"], "add": ["Viral Enhancers"]},
    "Robinson Industries": {"remove": ["Diverse production strategy", "Diversifier milestone"], "add": ["Strip Mine", "Business Empire", "Cartel", "Fuel Factory"]},
    "Inventrix": {"remove": ["Science cards", "Cards с strict requirements"], "add": ["Research", "Adaptation Technology", "Special Design"]},
    "Mons Insurance": {"remove": ["High MC production cards"], "add": ["Business Empire", "Cartel", "Sponsors", "Acquired Company"]},
    "Sagitta Frontier Services": {"remove": ["No-tag cards", "Single-tag cards"], "add": ["Acquired Company", "Directed Heat Usage", "Caretaker Contract"]},
    "Viron": {"remove": ["Animal VP cards"], "add": ["Birds", "Fish"]},
    "Aridor": {"remove": ["diverse tag карты"], "add": []},
    "Mining Guild": {"remove": ["Builder milestone", "Miner award"], "add": ["Strip Mine", "Mining Area"]},
    "PhoboLog": {"remove": ["Titanium production cards", "Space events"], "add": ["Titanium Mine", "Asteroid Mining", "Deimos Down"]},
    "Pristar": {"remove": ["Reds party", "VP cards without TR", "Late-game mass terraform", "Non-terraforming production"], "add": ["Birds", "Fish", "Pets", "Predators", "Strip Mine"]},
    "Factorum": {"remove": ["Colonies (trade)"], "add": ["Electro Catapult", "Steelworks"]},
    "Palladin Shipping": {"remove": ["Space cards", "Pathfinder planetary tracks"], "add": ["Titan Shuttles", "Saturn Surfing"]},
    "Tycho Magnetics": {"remove": ["Energy production cards"], "add": []},
    "Thorgate": {"remove": ["Energy-consuming cards", "Colonies"], "add": ["Electro Catapult", "AI Central"]},
    "Utopia Invest": {"remove": ["Robinson Industries (Merger)", "Steel and titanium cards", "Late-game resource conversion"], "add": ["Strip Mine", "Advanced Alloys", "Merger", "Space Elevator"]},
    "Stormcraft Incorporated": {"remove": ["Floater cards", "Jovian multipliers"], "add": ["Dirigibles", "Stratospheric Birds", "Atmoscoop"]},
    "Celestic": {"remove": ["Hoverlord milestone"], "add": ["Atmo Collectors"]},
    "Pharmacy Union": {"remove": ["Science tag cards", "Quick flip strategy"], "add": ["Research", "Lagrange Observatory", "Physics Complex"]},
    "Aphrodite": {"remove": ["Morning Star Inc (Merger)"], "add": ["Merger"]},
    "Kuiper Cooperative": {"remove": ["Non-event Space cards"], "add": ["Titan Shuttles", "Saturn Surfing", "Satellites"]},
    "Recyclon": {"remove": ["Building tag cards", "Building tag preludes"], "add": ["Electro Catapult", "Medical Lab", "Smelting Plant"]},
    "Splice": {"remove": ["Microbe cards"], "add": ["Symbiotic Fungus", "Extreme-Cold Fungus", "Tardigrades"]},
    "United Nations Mars Initiative": {"remove": ["Terraforming-focused cards", "Terraformer milestone"], "add": ["Terraforming Contract", "Terraforming Deal", "Nitrogen-Rich Asteroid", "Giant Ice Asteroid"]},
    "Terralabs Research": {"remove": ["Science tag cards", "Earth tag discounts"], "add": ["Research", "Olympus Conference", "Earth Office"]},
    "Mars Maths": {"remove": ["Science tag cards"], "add": ["Physics Complex", "AI Central"]},
    "Helion": {"remove": ["Heat Trappers"], "add": []},
    "High Circles": {"remove": ["Turmoil-heavy strategies"], "add": ["Cultural Metropolis"]},
    "Huge Asteroid": {"remove": ["Temperature-gated cards", "TR rush strategies", "Insects/Methane From Titan"], "add": ["Insects", "Methane From Titan", "Adaptation Technology"]},
    "UNMI Contractor": {"remove": ["Terraformer milestone"], "add": ["Terraforming Contract"]},
    "Experimental Forest": {"remove": ["NRA (Nitrogen-Rich Asteroid)", "Gardener milestone", "Tharsis (placement bonuses)"], "add": ["Nitrogen-Rich Asteroid", "Insects"]},
    "Soil Bacteria": {"remove": ["Ecologist milestone"], "add": []},
    "Double Down": {"remove": ["Great Aquifer (x2 = 4 oceans)", "Huge Asteroid (x2 = 6 temp)", "Business Empire (x2 = 12 MC-prod)", "Allied Bank (x2 = 8 MC-prod)", "UNMI Contractor (x2 = 6 TR)"], "add": ["Great Aquifer", "Huge Asteroid", "Business Empire", "Allied Bank", "UNMI Contractor"]},
    "Polar Industries": {"remove": ["Rush strategies"], "add": ["Nitrogen-Rich Asteroid"]},
    "Strategic Base Planning": {"remove": ["Tharsis (Mayor)", "Colony games", "Energy production hands"], "add": ["Power Infrastructure", "Electro Catapult", "Mining Colony"]},
    "Research Network": {"remove": ["Jovian multipliers", "Any tag-dependent milestone"], "add": ["Terraforming Ganymede", "Io Mining Industries"]},
    "Space Lanes": {"remove": ["Colony-heavy games"], "add": []},
    "Aquifer Turbines": {"remove": ["Colonies (trading)"], "add": ["Power Infrastructure"]},
    "Merger": {"remove": ["Valley Trust (9 preludes to look at)", "Any strong corp combination"], "add": ["Valley Trust", "Double Down"]},
    "Smelting Plant": {"remove": ["Building card hands", "O2 requirement cards"], "add": ["Electro Catapult", "Space Elevator"]},
    "Supply Drop": {"remove": ["Mixed building+space hands", "Ecoline (plants)"], "add": ["Advanced Alloys", "Electro Catapult"]},
    "World Government Advisor": {"remove": ["TR rush strategies", "Venus strategies (raise Venus)"], "add": ["Terraforming Contract", "Venus Governor"]},
    "Corridors of Power": {"remove": ["Turmoil-heavy strategies", "Septum Tribus"], "add": ["Septem Tribus", "Cultural Metropolis"]},
    "Rise To Power": {"remove": ["Turmoil strategies", "Septum Tribus", "Political lobbying"], "add": ["Septem Tribus", "Cultural Metropolis", "Banned Delegate"]},
    "Supplier": {"remove": ["Colonies (trading)", "Building hands"], "add": ["Power Infrastructure", "Electro Catapult"]},
    "Focused Organization": {"remove": ["Card-cycling strategies", "Viron (double action)", "Corps с card draw benefits"], "add": ["Viron", "AI Central", "Restricted Area"]},
    "Power Generation": {"remove": ["Colonies (trading)"], "add": ["Power Infrastructure"]},
    "Mining Operations": {"remove": ["Steel-heavy hands"], "add": ["Electro Catapult"]},
    "Terraforming Deal": {"remove": ["TR rush strategies"], "add": []},
    "Donation": {"remove": ["Expensive gen 1 cards", "Any corp with low starting MC"], "add": ["Terraforming Ganymede", "Large Convoy"]},
    "Venus L1 Shade": {"remove": ["Venus requirement cards"], "add": ["Stratospheric Birds"]},
    "Eccentric Sponsor": {"remove": ["Any 25+ MC engine card"], "add": ["Anti-Gravity Technology"]},
    "Industrial Complex": {"remove": ["Loan (combo)", "Zero-production corps"], "add": ["Loan", "Business Empire"]},
    "Old Mining Colony": {"remove": ["Colony games", "Space card hands"], "add": ["Rim Freighters", "Cryo-Sleep"]},
    "Recession": {"remove": ["Aggressive rush strategies", "Early tempo plays", "When opponents are cash-poor"], "add": ["Terraforming Contract", "Nitrogen-Rich Asteroid"]},
    "Main Belt Asteroids": {"remove": ["Asteroid cards"], "add": ["Asteroid Mining", "Asteroid Mining Consortium"]},
    "Floating Trade Hub": {"remove": ["Floater cards"], "add": ["Titan Floating Launch-pad"]},
    "Orbital Construction Yard": {"remove": ["Space card-heavy hands"], "add": ["Io Mining Industries", "Titan Shuttles"]},
    "Board of Directors": {"remove": ["Point Luna (Earth tag)", "Card-hungry strategies", "Viron (double action)"], "add": ["Point Luna", "Viron", "Restricted Area"]},
    "Self-Sufficient Settlement": {"remove": ["Mayor milestone", "Elysium (Olympus Mons)"], "add": ["Rover Construction", "Capital"]},
    "Martian Industries": {"remove": ["Colonies (trading)", "Steel-intensive hands"], "add": ["Power Infrastructure", "Space Elevator"]},
    "Mohole": {"remove": ["TR rush strategies"], "add": ["Caretaker Contract"]},
    "Early Settlement": {"remove": ["Mayor milestone (Tharsis)", "Ecoline (with city placement)"], "add": ["Rover Construction", "Capital"]},
    "Colony Trade Hub": {"remove": ["Colony-heavy games"], "add": ["Trade Fleet"]},
    "Giant Solar Collector": {"remove": ["Colonies (trading)", "Electrician award"], "add": ["Power Infrastructure", "AI Central"]},
    "Mohole Excavation": {"remove": ["Building tag cards"], "add": ["Electro Catapult"]},
    "Preservation Program": {"remove": ["TR rush strategies", "Terraformer milestone"], "add": []},
    "Venus Contract": {"remove": ["Venus strategy cards"], "add": []},
    "Nobel Prize": {"remove": ["VP-focused late strategies", "Wild tag requirements"], "add": ["Research Coordination", "Solarnet"]},
    "Loan": {"remove": ["Industrial Complex (combo)", "Expensive gen 1 cards"], "add": ["Industrial Complex", "Business Empire"]},
    "Io Research Outpost": {"remove": ["Jovian multipliers", "Scientist award"], "add": ["Terraforming Ganymede", "Io Mining Industries"]},
    "Applied Science": {"remove": ["Excentric award"], "add": ["AI Central"]},
    "Galilean Mining": {"remove": ["Jovian multipliers", "Rim Settler milestone"], "add": ["Terraforming Ganymede", "Io Mining Industries"]},
    "Biosphere Support": {"remove": ["NRA (if +3 plant tags)"], "add": ["Nitrogen-Rich Asteroid"]},
    "Society Support": {"remove": ["Helion (slightly less bad)", "Nothing useful"], "add": ["Caretaker Contract", "GHG Factories"]},
    "Co-leadership": {"remove": ["Любая корпорация (CEO выбирается под неё)", "Strong prelude combos (если вторая прелюдия сильная)", "Гибкие стратегии"], "add": ["Double Down", "Huge Asteroid", "Business Empire"]},
    "Research Grant": {"remove": ["Researcher milestone", "Science-dependent cards"], "add": ["Mars University", "Olympus Conference"]},
    "Sky Docks": {"remove": ["Colony synergies (Cryo Sleep, Rim Freighters)", "Earth tag engine", "Point Luna", "Teractor"], "add": ["Cryo-Sleep", "Rim Freighters"]},
    "Research Outpost": {"remove": ["Any engine strategy", "Builder milestone", "Scientist award", "Mayor milestone", "Steel corps"], "add": ["Mars University", "Olympus Conference", "AI Central", "Restricted Area"]},
    "Solar Logistics": {"remove": ["Earth tag engine", "Space event strategies", "Earth Office", "Teractor", "Point Luna"], "add": ["Earth Office", "Sponsors", "Bribed Committee"]},
    "Spin-off Department": {"remove": ["Credicor (+4 MC per 20+ card + draw)", "Big space/building cards", "Point Luna"], "add": ["Terraforming Ganymede", "Deimos Down", "Large Convoy"]},
    "Giant Ice Asteroid": {"remove": ["Legend milestone", "Phobolog", "Media Group"], "add": ["Optimal Aerobraking", "Arctic Algae"]},
    "L1 Trade Terminal": {"remove": ["Trade fleet cards", "Poseidon"], "add": ["Trade Fleet", "Productive Outpost"]},
    "Protected Habitats": {"remove": ["Plant production cards", "Animal cards (Birds, Fish)", "NRA strategy", "Ecoline"], "add": ["Birds", "Fish", "Nitrogen-Rich Asteroid", "Penguins"]},
    "Deimos Down": {"remove": ["Legend milestone", "Phobolog", "Media Group", "Astra Mechanica"], "add": ["Media Group", "Optimal Aerobraking"]},
    "Psychrophiles": {"remove": ["Any plant-tag cards", "Microbe colonies", "Ecologist milestone", "Symbiotic Fungus"], "add": ["Nitrogen-Rich Asteroid", "Symbiotic Fungus", "Soil Studies"]},
    "Viral Enhancers": {"remove": ["Any 1-VP animal card"], "add": ["Birds"]},
    "Deimos Down:promo": {"remove": ["Legend milestone", "Phobolog", "Mining Guild"], "add": ["Optimal Aerobraking"]},
    "Nuclear Zone": {"remove": ["Terraformer milestone", "Helion", "Earth Office", "Teractor", "Point Luna"], "add": ["Terraforming Contract", "Adaptation Technology"]},
    "Research": {"remove": ["Science engine payoffs", "Scientist award", "Valley Trust"], "add": ["AI Central", "Physics Complex"]},
    "Space Port": {"remove": ["Colony strategies", "Steel corps", "Trade synergy cards", "Mayor milestone"], "add": ["Trade Fleet", "Rim Freighters", "Cryo-Sleep", "Productive Outpost"]},
    "Arctic Algae": {"remove": ["Plant protection cards", "Ecoline"], "add": ["Protected Habitats"]},
    "Dusk Laser Mining": {"remove": ["any science engine", "Phobolog", "Inventrix"], "add": ["Mars University", "Research"]},
    "Space Hotels": {"remove": ["Earth tag engine", "Banker/Specialist milestones", "Point Luna", "Teractor"], "add": ["Sponsors", "Luna Governor", "Earth Office"]},
    "Electro Catapult": {"remove": ["Steel production cards", "Mining Guild", "Interplanetary Cinematics", "Manutech", "Thorgate"], "add": ["Strip Mine", "Smelting Plant", "Mining Operations", "Advanced Alloys"]},
    "Red Spot Observatory": {"remove": ["Jovian multipliers", "Titan colony (floaters)", "Science engine", "Celestic/Stormcraft", "Rim Settler milestone"], "add": ["Terraforming Ganymede", "Io Mining Industries", "Mars University", "Olympus Conference"]},
    "Ganymede Colony": {"remove": ["Jovian tag cards", "Rim Settler milestone", "Phobolog"], "add": ["Vesta Shipyard", "Callisto Penal Mines"]},
    "Mass Converter": {"remove": ["Colonies (trading)"], "add": ["Warp Drive"]},
    "Quantum Communications": {"remove": ["Science engine cards", "Colony-heavy games", "Luna/Ceres/Pluto colonies", "Banker award"], "add": ["Research", "Productive Outpost", "Mining Colony", "Trade Fleet"]},
    "Red Ships": {"remove": ["Low-parameter strategies", "Any cheap engine", "Turmoil parties"], "add": ["Corridors of Power", "Rise To Power", "Cultural Metropolis"]},
    "Atalanta Planitia Lab": {"remove": ["Science engine", "Venuphile award", "Diversifier milestone", "Scientists award"], "add": ["Mars University", "Olympus Conference", "Research", "Venusian Animals"]},
    "Field-Capped City": {"remove": ["Mayor milestone", "Builder milestone", "Mining Guild", "Tharsis Republic", "Colonies trading"], "add": ["Rover Construction", "Capital", "Productive Outpost"]},
    "GMO Contract": {"remove": ["bio-tag heavy strategies", "Ecoline"], "add": ["Topsoil Contract"]},
    "Open City": {"remove": ["Mayor milestone", "Landlord award", "Mining Guild", "Manutech"], "add": ["Rover Construction", "Capital", "Immigrant City"]},
    "Frontier Town": {"remove": ["Mayor milestone", "Tharsis Republic", "Mining Guild", "specific map spots", "Mars First party"], "add": ["Rover Construction", "Open City", "Capital"]},
    "Martian Media Center": {"remove": ["Mars First party cards", "Mining Guild", "Tharsis Republic", "Credicor"], "add": ["Banned Delegate", "Cultural Metropolis"]},
    "Terraforming Contract": {"remove": ["Banker award", "Point Luna", "Teractor", "Earth Office", "Manutech"], "add": ["Terraforming Deal", "Nitrogen-Rich Asteroid", "Giant Ice Asteroid"]},
    "Warp Drive": {"remove": ["Science engine"], "add": ["AI Central"]},
    "Carbon Nanosystems": {"remove": ["Science engine cards", "Space cards", "City cards"], "add": ["AI Central", "Physics Complex", "Research"]},
    "Caretaker Contract": {"remove": ["Heat production cards", "Generalist milestone", "Helion"], "add": ["GHG Factories", "Soletta", "Solar Reflectors"]},
    "Ecology Research": {"remove": ["Diversifier milestone"], "add": []},
    "Event Analysts": {"remove": ["Science engine", "Turmoil-heavy games", "Scientist award"], "add": ["Corridors of Power", "Rise To Power"]},
    "Kaguya Tech": {"remove": ["Plant strategy", "Mayor milestone", "Landlord award", "City adjacency"], "add": ["Nitrogen-Rich Asteroid", "Open City", "Capital", "Rover Construction"]},
    "Lunar Mining": {"remove": ["Space card strategy", "Point Luna", "Teractor", "Earth Office"], "add": ["Io Mining Industries", "Titan Shuttles"]},
    "Predators": {"remove": ["Protected Habitats (counter)", "Inventrix"], "add": ["Large Convoy"]},
    "Research Coordination": {"remove": ["NRA (extra plant tag)", "Milestone claims", "Science requirements"], "add": ["Nitrogen-Rich Asteroid", "Solarnet"]},
    "Restricted Area": {"remove": ["Engine strategies", "Science milestones", "Pluto colony (card cycling)"], "add": ["AI Central", "Research"]},
    "Venusian Animals": {"remove": ["Science engine", "Card draw"], "add": ["Research", "Freyja Biodomes"]},
    "Colonial Representation": {"remove": ["Colony-heavy strategies", "Poseidon", "Aridor"], "add": ["Productive Outpost", "Mining Colony"]},
    "Hermetic Order of Mars": {"remove": ["Landlord strategies", "Manutech"], "add": ["Capital", "Open City"]},
    "Static Harvesting": {"remove": ["Building-heavy strategies", "Interplanetary Cinematics", "Mining Guild", "Manutech", "Thorgate"], "add": ["Electro Catapult", "Advanced Alloys", "Strip Mine"]},
    "Virus": {"remove": ["Anti-VP strategies"], "add": ["Media Group"]},
    "Flooding": {"remove": ["lakefront ocean strategy", "Legend milestone"], "add": ["Lakefront Resorts", "Kelp Farming"]},
    "Gene Repair": {"remove": ["Science engine", "Scientist award", "Banker award"], "add": ["Research", "AI Central"]},
    "Natural Preserve": {"remove": ["Builder milestone", "Scientist award", "Elysium 3-card spot", "Mining Guild"], "add": ["Research", "Physics Complex"]},
    "Ceres Tech Market": {"remove": ["Colony strategies", "Card-draw engines", "Point Luna"], "add": ["Productive Outpost", "Mining Colony"]},
    "Business Contacts": {"remove": ["Legend milestone", "Point Luna", "IC"], "add": ["Earth Office", "Sponsors"]},
    "Ishtar Expedition": {"remove": ["Venus strategy cards", "Phobolog", "Morning Star Inc"], "add": ["Venus Governor", "Stratospheric Birds", "Sulphur Exports"]},
    "Jovian Embassy": {"remove": ["Rim Settler milestone"], "add": ["Vesta Shipyard"]},
    "Rim Freighters": {"remove": ["Colony strategies", "Multiple trade fleets", "Space tag synergies"], "add": ["Trade Fleet", "Productive Outpost", "Cryo-Sleep"]},
    "Sister Planet Support": {"remove": ["Earth tag engines (Cartel, Miranda Resort)", "Specialist milestone", "Venus tag synergies"], "add": ["Cartel", "Miranda Resort", "Venus Governor"]},
    "Space Elevator": {"remove": ["IC (steel pile)", "Steel production preludes", "Mining Guild"], "add": ["Smelting Plant", "Mining Operations", "Electro Catapult"]},
    "Wildlife Dome": {"remove": ["Ecologist milestone", "Aridor"], "add": ["GMO Contract"]},
    "Business Network": {"remove": ["Engine strategies", "Point Luna", "Earth Office", "Teractor"], "add": ["Restricted Area", "Sponsors", "Earth Office"]},
    "Lagrange Observatory": {"remove": ["Science engine payoffs", "Phobolog"], "add": ["AI Central", "Olympus Conference"]},
    "Orbital Cleanup": {"remove": ["Science-heavy strategies", "Point Luna"], "add": ["Research", "Physics Complex"]},
    "Project Inspection": {"remove": ["1-VP animal cards", "Martian Zoo"], "add": ["Birds", "Fish"]},
    "Quantum Extractor": {"remove": ["Science engine", "Colonies (trading energy)"], "add": ["AI Central", "Strip Mine"]},
    "Saturn Surfing": {"remove": ["Hoverlord milestone", "Floater support cards", "Earth tag engines", "Point Luna", "Teractor"], "add": ["Dirigibles", "Titan Floating Launch-pad", "Luna Governor", "Sponsors"]},
    "Solar Wind Power": {"remove": ["Aridor (3 new tags)", "Science/Space/Power milestones", "Colonies (energy for trading)", "Diversifier"], "add": ["Power Infrastructure", "AI Central", "Strip Mine"]},
    "Sponsored Academies": {"remove": ["Science engine", "AGT unlock", "Earth Office"], "add": ["AI Central", "Anti-Gravity Technology"]},
    "Zeppelins": {"remove": ["Banker award", "City-heavy boards", "Zeppelin card draw", "Late game MC dump", "Tharsis Republic"], "add": ["Open City", "Capital", "Immigrant City"]},
    "Productive Outpost": {"remove": ["Colony-heavy strategies", "Poseidon", "Aridor"], "add": ["Mining Colony", "Trade Fleet", "Cryo-Sleep"]},
    "Rover Construction": {"remove": ["City-placing strategies", "Mining Guild", "Steel production"], "add": ["Open City", "Capital", "Stanford Torus"]},
    "Asteroid Mining Consortium": {"remove": ["Phobolog (as attacker)", "Rim Settler milestone", "Jovian multipliers"], "add": ["Io Mining Industries", "Titanium Mine", "Vesta Shipyard"]},
    "Giant Solar Shade": {"remove": ["Venus requirement cards", "Venuphile award", "Phobolog"], "add": ["Stratospheric Birds", "Venus Governor"]},
    "Mining Rights": {"remove": ["Landlord award", "Tharsis map steel/ti spots", "Mining Guild", "Phobolog"], "add": ["Mining Area", "Advanced Alloys"]},
    "Soil Studies": {"remove": ["Venus strategies", "Colony strategies"], "add": ["Venus Soils", "Mining Colony"]},
    "Neptunian Power Consultants": {"remove": ["Ocean placement strategies", "Thorgate", "Manutech"], "add": ["Giant Ice Asteroid", "Kelp Farming"]},
    "Convoy From Europa": {"remove": ["Tharsis 2-card ocean spot", "Phobolog"], "add": ["Arctic Algae"]},
    "Galilean Waystation": {"remove": ["Rim Settler milestone", "Jovian multipliers"], "add": ["Saturn Systems"]},
    "Industrial Microbes": {"remove": ["Ecologist milestone"], "add": []},
    "Peroxide Power": {"remove": ["Colonies (trading)", "Builder milestone"], "add": ["Power Infrastructure", "Steelworks"]},
    "Protected Valley": {"remove": ["IC (steel)", "Gardener milestone", "Estate Dealer (Elysium)", "Mining Guild", "Credicor"], "add": ["Nitrogen-Rich Asteroid", "Insects"]},
    "Solar Reflectors": {"remove": ["Phobolog (ti payment)", "Thermalist award", "Rush strategy"], "add": ["Caretaker Contract", "GHG Factories"]},
    "Space Station": {"remove": ["Space tag engine", "Other space discounts (stackable)", "Phobolog"], "add": ["Mass Converter", "Quantum Extractor", "Warp Drive"]},
    "Titan Floating Launch-pad": {"remove": ["Hoverlord milestone"], "add": ["Dirigibles"]},
    "Titanium Mine": {"remove": ["Space cards", "Steel-payable cards", "Builder milestone", "Phobolog"], "add": ["Io Mining Industries", "Titan Shuttles", "Deimos Down"]},
    "Corona Extractor": {"remove": ["Colonies (trading)", "Science engine", "City cards"], "add": ["Power Infrastructure", "AI Central", "Strip Mine"]},
    "Directed Heat Usage": {"remove": ["any heat production", "Helion", "Sagitta"], "add": ["GHG Factories", "Soletta", "Solar Reflectors"]},
    "Floyd Continuum": {"remove": ["Science engine", "late game economy", "Venus inclusion", "Viron"], "add": ["Viron", "Mars University", "Olympus Conference"]},
    "Great Dam:promo": {"remove": ["Builder milestone", "Colonies trading"], "add": ["Power Infrastructure"]},
    "Noctis City": {"remove": ["Mayor milestone", "Tharsis map", "Greenery placement", "Steel payment"], "add": ["Rover Construction", "Capital"]},
    "Plantation": {"remove": ["Gardener milestone", "Mars University (for req)"], "add": ["Mars University", "Ecological Zone"]},
    "Self-replicating Robots": {"remove": ["Viron (double action)", "Big space/building cards (Deimos Down, Io Mining)", "Science engine"], "add": ["Viron", "Deimos Down", "Io Mining Industries", "Mars University"]},
    "Lava Flows": {"remove": ["Mining Guild (tile adjacency)", "Landlord strategies", "Temperature-dependent cards"], "add": ["Mining Area", "Adaptation Technology"]},
    "Bribed Committee": {"remove": ["Legend milestone", "Point Luna", "Teractor", "IC"], "add": ["Media Group", "Optimal Aerobraking"]},
    "Cryo-Sleep": {"remove": ["Colonies (trading)", "Multiple trade fleets", "Science engine"], "add": ["Trade Fleet", "Rim Freighters", "Productive Outpost"]},
    "GHG Factories": {"remove": ["Thermalist award", "Helion", "Mining Guild"], "add": ["Caretaker Contract", "Insects"]},
    "Great Dam": {"remove": ["Builder milestone", "Colonies trading"], "add": ["Power Infrastructure"]},
    "Power Plant": {"remove": ["Builder milestone", "Thorgate", "Cheung Shing Mars"], "add": ["Power Infrastructure", "Strip Mine"]},
    "Refugee Camps": {"remove": ["Diversifier milestone (unique resource)", "High MC-prod engines", "Earth tag synergies"], "add": ["Business Empire", "Cartel", "Sponsors"]},
    "Soil Enrichment": {"remove": ["Microbe cards with spare resources"], "add": ["Symbiotic Fungus"]},
    "Sponsors": {"remove": ["Banker award", "Point Luna", "Teractor", "Earth Office"], "add": ["Cartel", "Luna Governor", "Earth Office"]},
    "Toll Station": {"remove": ["Banker award", "Space-heavy opponents", "Phobolog", "Point Luna metagame", "Titanium payment"], "add": ["Satellites", "Space Hotels"]},
    "Worms": {"remove": ["Ecologist milestone"], "add": []},
    "Protected Growth": {"remove": ["Energy-heavy strategies", "Thorgate"], "add": ["Nuclear Power", "Power Plant"]},
    "Artificial Lake": {"remove": ["Estate Dealer award"], "add": ["Lakefront Resorts"]},
    "Crash Site Cleanup": {"remove": ["Legend milestone", "IC"], "add": ["Asteroid", "Deimos Down"]},
    "Io Sulphur Research": {"remove": ["Science engine", "Venus tag strategy", "Jovian multipliers"], "add": ["Terraforming Ganymede", "Mars University", "Olympus Conference"]},
    "Jovian Envoys": {"remove": ["Turmoil party strategy", "Jovian strategy", "Chairman control"], "add": ["Corridors of Power", "Rise To Power", "Terraforming Ganymede"]},
    "Local Heat Trapping": {"remove": ["1VP animal cards", "Helion", "High heat production"], "add": ["Birds", "Fish", "Livestock"]},
    "Medical Lab": {"remove": ["Builder milestone", "Scientist award", "Mining Guild", "Interplanetary Cinematics"], "add": ["Electro Catapult", "Power Plant", "Open City"]},
    "Molecular Printing": {"remove": ["Science-heavy strategies", "Late-game play"], "add": ["Research", "AI Central"]},
    "Public Baths": {"remove": ["Steel corps (IC, Mining Guild)", "Builder milestone", "Credicor (total cost 20+)"], "add": ["Strip Mine", "Power Plant", "Electro Catapult"]},
    "Vesta Shipyard": {"remove": ["Rim Settler milestone", "Jovian multipliers"], "add": ["Ganymede Colony", "Callisto Penal Mines"]},
    "Energy Tapping": {"remove": ["Energy-dependent strategies", "Thorgate", "Power tag requirements"], "add": ["Power Infrastructure", "AI Central"]},
    "Summit Logistics": {"remove": ["Colony strategies", "Turmoil Scientists party", "Building+Space engines"], "add": ["Corridors of Power", "Rise To Power"]},
    "Vermin": {"remove": ["City-light strategies"], "add": []},
    "Breathing Filters": {"remove": ["Science requirement cards", "Scientist award", "Diversifier milestone"], "add": ["Mars University", "Research", "AI Central"]},
    "Building Industries": {"remove": ["Builder milestone", "Contractor award"], "add": ["Electro Catapult", "Space Elevator"]},
    "Diaspora Movement": {"remove": ["Rim Settler milestone", "PhoboLog"], "add": ["Callisto Penal Mines"]},
    "Lake Marineris": {"remove": ["Heat rush strategy"], "add": ["Kelp Farming"]},
    "Lichen": {"remove": ["Ecologist milestone"], "add": []},
    "Lightning Harvest": {"remove": ["Science engine", "Colony trading", "Energizer milestone"], "add": ["Research", "Power Infrastructure", "AI Central"]},
    "Nuclear Power": {"remove": ["Colonies (trading)"], "add": ["Power Infrastructure"]},
    "Rad-Chem Factory": {"remove": ["Steel corps", "Terraformer milestone", "Colonies (spare energy)"], "add": ["Strip Mine", "Terraforming Contract", "Power Infrastructure"]},
    "Rego Plastics": {"remove": ["IC (20 steel)", "Steel production preludes", "Building-heavy strategies", "Mining Guild"], "add": ["Smelting Plant", "Mining Operations", "Electro Catapult"]},
    "Shuttles": {"remove": ["Space-heavy engine", "Mass Converter/Quantum Extractor", "Phobolog"], "add": ["Mass Converter", "Quantum Extractor", "Warp Drive"]},
    "Solarnet": {"remove": ["Multi-tag strategies", "Diversifier milestone", "Forecaster award"], "add": ["Research Coordination", "Soil Studies", "Stratospheric Expedition"]},
    "Subterranean Reservoir": {"remove": ["Legend milestone", "IC rebate"], "add": ["Kelp Farming", "Lakefront Resorts"]},
    "Venus Governor": {"remove": ["Venuphile award", "Morning Star Inc"], "add": ["Sulphur Exports", "Stratospheric Birds"]},
    "Venus Trade Hub": {"remove": ["Venuphile award", "Colonies trading", "Morning Star Inc", "Titanium"], "add": ["Trade Fleet", "Productive Outpost", "Rim Freighters"]},
    "Corporate Stronghold": {"remove": ["Mayor milestone", "Mining Guild", "Manutech", "Steel production", "Early economy"], "add": ["Rover Construction", "Immigrant City", "Capital"]},
    "Media Archives": {"remove": ["Event-heavy strategies", "Point Luna", "Teractor", "Earth Office"], "add": ["Bribed Committee", "Sponsors", "Luna Governor"]},
    "Spin-Inducing Asteroid": {"remove": ["Venus payoff cards", "Space/event discounts"], "add": ["Venus Governor", "Stratospheric Birds"]},
    "Beam From A Thorium Asteroid": {"remove": ["Colonies (trading)", "Hellas milestones", "Jovian multipliers", "Phobolog"], "add": ["Power Infrastructure", "Terraforming Ganymede", "Io Mining Industries"]},
    "GHG Import From Venus": {"remove": ["Thermalist award", "Phobolog"], "add": ["Caretaker Contract"]},
    "Industrial Center": {"remove": ["Builder milestone", "Landlord award", "Mining Guild"], "add": ["Open City", "Capital", "Rover Construction"]},
    "Omnicourt": {"remove": ["Steel-heavy strategies", "Builder milestone", "Terraformer milestone", "Mining Guild"], "add": ["Strip Mine", "Terraforming Contract", "Advanced Alloys"]},
    "Political Alliance": {"remove": ["Legend milestone", "Turmoil influence strategies", "Interplanetary Cinematics"], "add": ["Corridors of Power", "Rise To Power"]},
    "Power Supply Consortium": {"remove": ["Wild tag cards", "Colonies (deny trading energy)", "Power tag preludes", "Thorgate"], "add": ["Nuclear Power", "Power Plant", "Research Coordination"]},
    "Red Appeasement": {"remove": ["Reds political strategy", "Engine builders with low TR"], "add": ["Corridors of Power", "Rise To Power"]},
    "Solar Probe": {"remove": ["Mass Converter/Warp Drive (space discounts)", "Heavy science engine"], "add": ["Mass Converter", "Warp Drive"]},
    "Soletta": {"remove": ["Phobolog (ti payment)", "Insulation (convert to MC-prod)"], "add": ["Insulation", "Caretaker Contract"]},
    "Sponsored Mohole": {"remove": ["Kelvinists political strategy", "Heat/rush strategy", "Builder milestone", "Colonies (Kelvinists energy)"], "add": ["GHG Factories", "Caretaker Contract", "Strip Mine"]},
    "Venus Allies": {"remove": ["Venuphile award", "Multiple colonies", "Titanium", "Venus requirements", "Aphrodite"], "add": ["Productive Outpost", "Venus Governor", "Stratospheric Birds", "Sulphur Exports"]},
    "Corroder Suits": {"remove": ["Venuphile award", "Diversifier milestone"], "add": ["Sulphur Exports", "Gyropolis"]},
    "Aqueduct Systems": {"remove": ["Cheung Shing MARS (-2 MC building)", "Ceres colony (steel)", "Tharsis (Mayor + Builder)", "Contractor award", "Architect milestone", "Capital (city adj ocean)", "Mining Guild"], "add": ["Capital", "Open City", "Arctic Algae", "Kelp Farming"]},
    "Floating Habs": {"remove": ["Hoverlord milestone", "Titan colony"], "add": ["Titan Floating Launch-pad"]},
    "Fueled Generators": {"remove": ["Builder milestone", "city cards", "Colonies trading"], "add": ["Power Infrastructure", "Open City"]},
    "New Holland": {"remove": ["Mayor milestone", "City-heavy strategies", "Tharsis Republic"], "add": ["Rover Construction", "Open City"]},
    "PR Office": {"remove": ["Earth tag strategies", "Teractor", "Point Luna", "Earth Office", "Unity party"], "add": ["Sponsors", "Luna Governor", "Cartel"]},
    "Recruitment": {"remove": ["Turmoil strategies", "IC/Media Group (event discounts)", "Chairman-dependent cards"], "add": ["Corridors of Power", "Rise To Power", "Cultural Metropolis"]},
    "Satellites": {"remove": ["Space tag heavy strategies", "Banker award", "Phobolog"], "add": ["Space Station", "Toll Station", "Shuttles"]},
    "Tropical Resort": {"remove": ["Banker award", "Builder milestone", "Steel dump", "Temperature maxed", "Helion"], "add": ["Acquired Company", "Sponsors", "Cartel"]},
    "Martian Lumber Corp": {"remove": ["Building-heavy strategies"], "add": ["Electro Catapult"]},
    "Airliners": {"remove": ["Floater strategies", "Celestic"], "add": ["Titan Floating Launch-pad"]},
    "ArchaeBacteria": {"remove": ["Nitrogen Rich Asteroid (needs plant tag instead)"], "add": ["Nitrogen-Rich Asteroid"]},
    "Artificial Photosynthesis": {"remove": ["Science requirement cards", "Colonies (energy for trading)"], "add": ["AI Central", "Power Infrastructure"]},
    "SF Memorial": {"remove": ["Builder milestone", "Steel production/surplus", "Card draw engines"], "add": ["Strip Mine", "Smelting Plant"]},
    "Wave Power": {"remove": ["Thorgate (discount)", "Builder milestone", "Colonies trading", "Energy needs"], "add": ["Power Infrastructure", "AI Central"]},
    "Supermarkets": {"remove": ["City-placing strategies", "Mayor milestone", "MC-prod engines"], "add": ["Open City", "Capital", "Immigrant City"]},
    "Cloud Tourism": {"remove": ["Hoverlord milestone", "Venuphile award", "Point Luna", "Earth Office"], "add": ["Dirigibles", "Titan Floating Launch-pad"]},
    "Community Services": {"remove": ["No-tag cards", "Sagitta corp"], "add": ["Acquired Company", "Caretaker Contract"]},
    "Geothermal Power": {"remove": ["Builder milestone", "Colonies trading"], "add": ["Power Infrastructure"]},
    "Robot Pollinators": {"remove": ["Plant-heavy strategies", "Sagitta (no-tag bonus)"], "add": ["Nitrogen-Rich Asteroid", "Insects"]},
    "Special Permit": {"remove": ["Greens political strategy", "NRA (plant tag)", "Greenery strategies", "Plant tag synergies"], "add": ["Nitrogen-Rich Asteroid", "Insects", "Ecological Zone"]},
    "Supercapacitors": {"remove": ["Industrialist award", "Aridor", "Colonies trading"], "add": ["Strip Mine", "Power Infrastructure"]},
    "Water to Venus": {"remove": ["Legend milestone", "IC rebate", "Space discounts", "Venus requirements"], "add": ["Venus Governor", "Stratospheric Birds"]},
    "Windmills": {"remove": ["Thorgate (-3 MC discount)", "AI Central (needs energy)", "Colonies trading (energy for fleet)", "Builder milestone", "Steel dump"], "add": ["Power Infrastructure", "AI Central", "Strip Mine"]},
    "Biomass Combustors": {"remove": ["Energy-dependent strategies", "Building engines", "Thorgate", "Manutech"], "add": ["Power Infrastructure", "Strip Mine"]},
    "House Printing": {"remove": ["Building-heavy strategies", "Steel consumers", "Interplanetary Cinematics", "Mining Guild"], "add": ["Electro Catapult", "Space Elevator"]},
    "City Parks": {"remove": ["City-heavy strategies", "Builder milestone", "Mayor milestone", "Mining Guild"], "add": ["Open City", "Capital", "Stanford Torus"]},
    "Directed Impactors": {"remove": ["any ti production", "Phobolog"], "add": ["Titanium Mine", "Asteroid Mining"]},
    "Ironworks": {"remove": ["Builder milestone", "Manutech", "Energy Market", "Callisto colony"], "add": ["Strip Mine", "Power Infrastructure"]},
    "Local Shading": {"remove": ["Venus floater cards", "Venus tag strategy", "Banker award"], "add": ["Stratospheric Birds", "Venus Governor", "Sulphur Exports"]},
    "Mining Expedition": {"remove": ["Birds (enabling 13% O2)", "Interplanetary Cinematics"], "add": ["Birds"]},
    "Ore Processor": {"remove": ["Against plant-heavy opponents", "Physics Complex alternative"], "add": ["Strip Mine"]},
    "Public Celebrations": {"remove": ["Vitor (-3 MC)", "IC (-2 MC)", "Media Group (-3 MC)", "Legend milestone"], "add": ["Media Group"]},
    "Release of Inert Gases": {"remove": ["Terraformer milestone", "Legend milestone", "Benefactor award", "IC/Media Group"], "add": ["Terraforming Contract", "Media Group"]},
    "Search For Life": {"remove": ["Diversifier milestone", "Science requirements", "AI Central unlock", "Stall action value"], "add": ["Mars University", "Research"]},
    "Stanford Torus": {"remove": ["Mayor milestone", "Vitor"], "add": ["Open City", "Capital"]},
    "Unexpected Application": {"remove": ["Venuphile award", "Legend milestone", "Morning Star Inc", "Venus requirements", "Aphrodite"], "add": ["Venus Governor", "Stratospheric Birds"]},
    "Urbanized Area": {"remove": ["Mayor milestone", "Opponent's cities", "Steel payment", "Greenery adjacency", "Commercial District"], "add": ["Open City", "Capital", "Rover Construction"]},
    "Asteroid Deflection System": {"remove": ["VP strategies", "Triple tag synergies", "Phobolog", "Point Luna", "Mining Guild"], "add": ["Protected Habitats", "Arctic Algae"]},
    "Diversity Support": {"remove": ["Diverse resource strategies", "Floater+Microbe+Animal engines"], "add": ["Dirigibles", "Birds"]},
    "Venus Waystation": {"remove": ["Venus Governor (plays for free)", "Venus heavy strategy", "Venuphile award", "Morning Star Inc", "Titanium dump"], "add": ["Venus Governor", "Stratospheric Birds", "Sulphur Exports", "Venusian Animals"]},
    "Adapted Lichen": {"remove": ["Ecologist milestone"], "add": []},
    "Commercial District": {"remove": ["Banker award", "Landlord award", "Estate Dealer award", "Steel surplus"], "add": ["Open City", "Capital", "Urbanized Area"]},
    "Interplanetary Trade": {"remove": ["Diversifier milestone", "Banker award", "Phobolog"], "add": ["Research Coordination", "Solarnet"]},
    "Outdoor Sports": {"remove": ["Banker award", "Sagitta"], "add": ["Immigrant City"]},
    "Red Tourism Wave": {"remove": ["Reds political strategy", "Ground game with many tiles", "Earth tag synergies"], "add": ["Corridors of Power", "Sponsors"]},
    "Regolith Eaters": {"remove": ["Science engine (tag only)", "Decomposers (microbe tag)", "AI Central unlock"], "add": ["Decomposers", "AI Central", "Mars University"]},
    "Tundra Farming": {"remove": ["Banker award", "Plant tag synergies"], "add": ["Ecological Zone"]},
    "Carbonate Processing": {"remove": ["Thermalist award", "Generalist milestone", "Helion"], "add": ["Caretaker Contract", "GHG Factories"]},
    "Cloud Seeding": {"remove": ["Plant production strategy", "Generalist milestone"], "add": ["Nitrogen-Rich Asteroid", "Insects"]},
    "Energy Saving": {"remove": ["Thermalist award", "Tharsis Republic opponent", "Colonies trading"], "add": ["Power Infrastructure", "AI Central"]},
    "GHG Shipment": {"remove": ["Floater engine", "Thermalist award", "Helion"], "add": ["Dirigibles", "Caretaker Contract"]},
    "Ishtar Mining": {"remove": ["Venus tag strategy", "Morning Star Inc", "Inventrix"], "add": ["Venus Governor", "Stratospheric Birds"]},
    "Lava Tube Settlement": {"remove": ["Builder milestone", "Hellas map", "Mining Guild"], "add": ["Rover Construction", "Open City"]},
    "Public Plans": {"remove": ["Legend milestone", "Vitor", "IC"], "add": ["Media Group", "Sponsors"]},
    "Special Design": {"remove": ["Inventrix (+2 more = +4 total)", "Science event triggers (Mars U, IC, Media Group)"], "add": ["Inventrix", "Mars University"]},
    "Venusian Insects": {"remove": ["Ecologist milestone"], "add": []},
    "Venusian Plants": {"remove": ["Venuphile award", "Morning Star Inc"], "add": ["Venus Governor"]},
    "Extractor Balloons": {"remove": ["Hoverlord milestone", "Celestic", "Stormcraft"], "add": ["Dirigibles", "Titan Floating Launch-pad"]},
    "Great Escarpment Consortium": {"remove": ["steel-heavy strategies", "2P games", "Mining Guild"], "add": ["Strip Mine", "Advanced Alloys"]},
    "Neutralizer Factory": {"remove": ["Venus cards with requirements", "Venuphile award", "Morning Star Inc"], "add": ["Stratospheric Birds", "Venus Governor", "Venusian Animals"]},
    "Snow Algae": {"remove": ["Generalist milestone", "Insects (plant tag)", "Ecoline", "Tharsis Republic"], "add": ["Insects", "Nitrogen-Rich Asteroid"]},
    "Solar Power": {"remove": ["Builder milestone", "Steel dump", "Thorgate", "Vitor"], "add": ["Power Infrastructure", "Strip Mine"]},
    "Tardigrades": {"remove": ["Ecologist milestone"], "add": []},
    "Vote Of No Confidence": {"remove": ["Turmoil political events", "Delegate strategy", "Legend milestone (event)", "Chairman influence", "TR rush"], "add": ["Corridors of Power", "Rise To Power", "Cultural Metropolis"]},
    "Hackers": {"remove": ["None \u2014 take-that card, works against any opponent with MC-prod"], "add": []},
    "Callisto Penal Mines": {"remove": ["Rim Settler milestone", "Jovian multipliers", "Phobolog"], "add": ["Terraforming Ganymede", "Io Mining Industries"]},
    "Capital": {"remove": ["Estate Dealer award", "Mining Guild"], "add": ["Lakefront Resorts"]},
    "Forced Precipitation": {"remove": ["Venuphile award", "Venus tag for requirements"], "add": ["Titan Floating Launch-pad"]},
    "Sabotage": {"remove": ["IC (event rebate)", "Legend milestone", "Deny opponent milestones"], "add": ["Media Group", "Bribed Committee"]},
    "Colonial Envoys": {"remove": ["Colony-heavy strategy", "Turmoil manipulation"], "add": ["Productive Outpost", "Trade Fleet", "Corridors of Power"]},
    "Rad-Suits": {"remove": ["Vitor (-3 MC)", "Requirement milestones"], "add": ["Adaptation Technology"]},
    "Sulphur Exports": {"remove": ["Venuphile award", "Morning Star Inc"], "add": ["Gyropolis", "Corroder Suits"]},
    "Black Polar Dust": {"remove": ["Ecoline (needs heat)", "Thermalist award", "Helion"], "add": ["GHG Factories", "Caretaker Contract"]},
    "Aerosport Tournament": {"remove": ["Floater engines", "City-heavy games"], "add": ["Dirigibles", "Titan Floating Launch-pad"]},
    "Banned Delegate": {"remove": ["Turmoil parties", "Chairman strategies", "IC (event cashback)"], "add": ["Corridors of Power", "Rise To Power", "Media Group"]},
    "Land Claim": {"remove": ["Legend milestone"], "add": []},
    "Magnetic Field Generators": {"remove": ["Science engine excess energy", "Builder milestone", "Last-gen steel dump"], "add": ["Strip Mine", "Power Infrastructure"]},
    "Parliament Hall": {"remove": ["Builder milestone", "Mars First party", "Steel payment", "Mining Guild"], "add": ["Strip Mine", "Electro Catapult"]},
    "Power Grid": {"remove": ["Mass Converter requirement cards", "Colonies (multi-fleet)", "Thorgate"], "add": ["Mass Converter", "Power Infrastructure"]},
    "Space Mirrors": {"remove": ["Colonies (emergency energy)", "Power+Space tag needs"], "add": ["Power Infrastructure", "AI Central"]},
    "Food Factory": {"remove": ["Building strategies", "Steel production", "MC-prod engines"], "add": ["Insects", "Ecological Zone"]},
    "Titan Air-scrapping": {"remove": ["Jovian strategies", "Hoverlord milestone", "Phobolog"], "add": ["Terraforming Ganymede", "Io Mining Industries"]},
    "Rotator Impacts": {"remove": ["Aphrodite (Venus raises)", "Space engines", "Venus-light games for requirement"], "add": ["Venus Governor", "Stratospheric Birds"]},
    "Insulation": {"remove": ["Banker award", "Manutech"], "add": ["Soletta", "GHG Factories", "Solar Reflectors"]},
    "Martian Rails": {"remove": ["City-heavy strategies", "Colonies (for energy)", "Tharsis Republic"], "add": ["Open City", "Capital", "Stanford Torus"]},
    "Power Infrastructure": {"remove": ["Builder milestone", "Diversifier milestone", "Factorum", "Cheap tag filler"], "add": ["Strip Mine", "Nuclear Power", "AI Central"]},
    "Soil Factory": {"remove": ["Builder milestone (desperate)", "Steel dump only"], "add": ["Nitrogen-Rich Asteroid"]},
    "Stratopolis": {"remove": ["Hoverlord milestone"], "add": ["Titan Floating Launch-pad"]},
    "St. Joseph of Cupertino Mission": {"remove": ["City-heavy strategies", "VP accumulation"], "add": ["Open City", "Capital"]},
    "Air Raid": {"remove": ["Legend milestone", "Media Group", "Interplanetary Cinematics", "Titan colony"], "add": ["Media Group", "Bribed Committee"]},
    "Impactor Swarm": {"remove": ["Thermalist award", "Helion"], "add": ["Caretaker Contract"]},
    "Micro-Mills": {"remove": ["Generalist milestone", "Thermalist award"], "add": ["GHG Factories", "Caretaker Contract"]},
    "Security Fleet": {"remove": ["Phobolog (only)", "Excess titanium with no space cards"], "add": ["Titanium Mine", "Asteroid Mining"]},
    "Thermophiles": {"remove": ["Ecologist milestone"], "add": []},
    "Underground City": {"remove": ["Mayor milestone", "Steel dump late game", "Excess energy"], "add": ["Rover Construction"]},
    "Jet Stream Microscrappers": {"remove": ["Hoverlord milestone", "Titan colony"], "add": ["Titan Floating Launch-pad", "Dirigibles"]},
    "Dust Seals": {"remove": ["Tactician milestone", "Vitor", "Sagitta"], "add": ["Adaptation Technology"]},
    "Orbital Reflectors": {"remove": ["Venuphile award", "Morning Star Inc"], "add": ["Venus Governor"]},
    "Communication Center": {"remove": ["Event-heavy strategies", "Odyssey"], "add": ["Bribed Committee", "Sponsors"]},
    "Hydrogen Processing Plant": {"remove": ["Engine builds that need more time", "Ares hazard manipulation"], "add": ["Adaptation Technology", "Insects"]},
    "Envoys from Venus": {"remove": ["Venus strategy", "Turmoil"], "add": ["Venus Governor", "Corridors of Power"]},
    "Spin-inducing Asteroid": {"remove": ["Venus strategy", "Ti production"], "add": ["Venus Governor", "Stratospheric Birds", "Optimal Aerobraking"]},
    "Apollo": {"remove": ["Moon corporations (Luna First)", "Moon tile strategies", "Heavy Moon card drafting", "Luna Mining"], "add": ["Lunar Embassy"]},
    "Asimov": {"remove": ["Любая корпорация с сильной специализацией (Phobolog для Miner, Ecoline для Mayor)", "Award-heavy стратегии", "Diversified engines (чтобы быть 2nd+ в нескольких наградах)"], "add": ["Strip Mine", "Research", "Terraforming Ganymede"]},
    "Clarke": {"remove": ["EcoLine (extra plant value, high plant-prod)", "Helion (heat as MC)", "Mining Guild (greenery push)", "Plant production preludes", "Greenery-heavy strategies"], "add": ["Nitrogen-Rich Asteroid", "Insects", "Kelp Farming", "Protected Habitats"]},
    "Duncan": {"remove": ["Любая корпорация (универсальный)", "MC-hungry стратегии (late OPG)", "VP-focused (early OPG gen 1-2)"], "add": ["Birds", "Strip Mine", "Terraforming Ganymede"]},
    "Faraday": {"remove": ["Point Luna (Earth tags)", "Interplanetary Cinematics (Building tags)", "Splice (Microbe tags)", "Tag-heavy strategies", "Science-focused builds"], "add": ["Sponsors", "Electro Catapult", "Decomposers", "Research"]},
    "Floyd": {"remove": ["Expensive cards (Terraforming Ganymede, Great Dam, etc.)", "Card-draw corps (Point Luna, Terralabs)", "Holding expensive cards for optimal timing"], "add": ["Terraforming Ganymede", "Deimos Down", "Large Convoy", "Anti-Gravity Technology"]},
    "Gordon": {"remove": ["EcoLine (many greeneries)", "Tharsis Republic (cities)", "Mining Guild (steel + tile placement)", "Any tile-heavy strategy", "Mayor/Builder milestones"], "add": ["Open City", "Capital", "Lava Flows", "Mohole Area"]},
    "Greta": {"remove": ["Any TR-raising strategy", "Standard project Greenery/Asteroid", "Temperature/Oxygen raising cards", "Terraforming-heavy strategies", "Cards with multiple TR raises"], "add": ["Terraforming Contract", "Giant Ice Asteroid", "Nitrogen-Rich Asteroid", "Deimos Down"]},
    "HAL 9000": {"remove": ["Late game burst (gen 7-8)", "Manutech (production raise triggers)", "When you need resources NOW for final push"], "add": ["Strip Mine", "Business Empire", "Large Convoy"]},
    "Ingrid": {"remove": ["EcoLine (many greeneries)", "Tharsis Republic (cities)", "Tile-heavy strategies", "Gordon (if both available \u2014 dream combo)"], "add": ["Open City", "Capital", "Gordon"]},
    "Musk": {"remove": ["Phobolog (+1 Ti value = ceiling 40+ MC)", "Point Luna (draw Earth cards \u2192 сбросить лишние)", "Space tag strategy", "Ti-payable cards"], "add": ["Io Mining Industries", "Deimos Down", "Titan Shuttles"]},
    "Rogers": {"remove": ["Venus tag cards"], "add": []},
    "Ryu": {"remove": ["Любая корпорация с 4+ MC-prod (swap в Ti/Steel)", "Phobolog (Ti prod extra value)", "Space strategy (ti-prod)", "Building strategy (steel-prod)", "Helion (heat \u2192 ti swap)"], "add": ["Strip Mine", "Titanium Mine", "Business Empire"]},
    "Stefan": {"remove": ["Card draw corps (Point Luna, Inventrix)", "Planner milestone (16 cards)", "Card-heavy strategies", "Late game VP conversion"], "add": ["Research", "Restricted Area", "Mars University"]},
    "Tate": {"remove": ["Tag-focused strategies (Science, Jovian)", "Card synergy corps", "Milestone pursuit (specific tags)", "Award optimization"], "add": ["Terraforming Ganymede", "Research", "Io Mining Industries"]},
    "Ulrich": {"remove": ["Ocean-placing strategy", "Standard project funding", "Late game VP push"], "add": ["Giant Ice Asteroid", "Kelp Farming"]},
    "Van Allen": {"remove": ["Any corp (universal)", "Flexible strategies (multi-tag)", "Milestone-oriented play", "Ecoline (Gardener)", "IC (Builder)", "Tharsis Republic (Mayor)"], "add": ["Open City", "Strip Mine", "Research", "Nitrogen-Rich Asteroid"]},
}

final_fixes = []

for card_name, card_data in evals.items():
    synergies = card_data.get("synergies", [])
    card_type = card_data.get("type", "")

    generic = [s for s in synergies if is_generic(s)]
    concrete = [s for s in synergies if not is_generic(s)]

    if card_type == 'project':
        corps_in_syn = [s for s in concrete if s in corp_names]
        if corps_in_syn:
            generic.extend(corps_in_syn)
            concrete = [s for s in concrete if s not in corp_names]

    if not generic:
        continue

    if card_name in manual_fixes:
        mf = manual_fixes[card_name]
        remove_list = list(mf["remove"])
        add_list = list(mf["add"])

        for g in generic:
            if g not in remove_list:
                remove_list.append(g)

        remaining = [s for s in synergies if s not in remove_list]
        add_list = [a for a in add_list if a not in remaining]

        total = len(remaining) + len(add_list)
        if total > 5:
            add_list = add_list[:max(0, 5 - len(remaining))]

        if remove_list or add_list:
            final_fixes.append({"card": card_name, "remove": remove_list, "add": add_list})
    else:
        final_fixes.append({"card": card_name, "remove": generic, "add": []})

print(json.dumps(final_fixes, indent=2, ensure_ascii=False))
